### ISSUE TITLE
上传文件遇到"连接被对方重设"异常

### ISSUE THREAD

**Issue by yhcc** [KOHGYLW/kiftd#121]
感谢你开源了这个云盘，非常简洁。部署完成之后，我通过admin用户登录，尝试上传文件时，遇到了以下的报错，
```
TYPE:
Exception
CONTENT:
org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: 连接被对方重设
        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:122)
        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:113)
        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:86)
        at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:93)
        at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1128)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:960)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
......
```

这种问题应该怎么解决呢？
PS: 我是通过mac上传的，不管chrome还是safari浏览器都会报这个错误。

前端会显示
提示：出现意外错误，文件：[readme.txt]上传失败，上传被中断。

**Comment by woshinidayezhang** [comment]
我也遇到同样的问题了.
内网使用没有问题,但是用的反向代理上传大文件就会出现这种问题
