### ISSUE TITLE
kiftd 在windows 服务器上启动失败，求解决方法

### ISSUE THREAD

**Issue by riverboat22** [KOHGYLW/kiftd#139]
E:\kiftd>java -jar kiftd-1.0.35-RELEASE.jar -start
[2020年12月01日 11:28:36]正在初始化服务器设置...

[2020年12月01日 11:28:36]正在载入配置文件...

[2020年12月01日 11:28:36]配置文件载入完毕。正在检查配置...

[2020年12月01日 11:28:36]正在检查服务器配置...

[2020年12月01日 11:28:36]检查完毕。

[2020年12月01日 11:28:36]准备就绪。

[2020年12月01日 11:28:36]正在检查服务器配置...

[2020年12月01日 11:28:36]检查完毕。

[2020年12月01日 11:28:36]正在开启服务器引擎...

2020-12-01 11:28:39.307 ERROR ??? --- [           main] o.s.boot.SpringApplicati
on               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web ser
ver; nested exception is org.springframework.boot.web.server.WebServerException:
 Unable to start embedded Tomcat
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-
2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:544) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.
RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.
0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:759) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:395) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:327) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at kohgylw.kiftd.server.ctl.KiftdCtl.start(KiftdCtl.java:64) [kiftd-1.0.
35-RELEASE.jar:1.0.35-RELEASE]
        at kohgylw.kiftd.mc.ConsoleRunner.execute(ConsoleRunner.java:88) [kiftd-
1.0.35-RELEASE.jar:1.0.35-RELEASE]
        at kohgylw.kiftd.mc.ConsoleRunner.build(ConsoleRunner.java:66) [kiftd-1.
0.35-RELEASE.jar:1.0.35-RELEASE]
        at kohgylw.kiftd.mc.MC.main(MC.java:48) [kiftd-1.0.35-RELEASE.jar:1.0.35
-RELEASE]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to sta
rt embedded Tomcat
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initiali
ze(TomcatWebServer.java:126) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(T
omcatWebServer.java:86) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFa
ctory.getTomcatWebServer(TomcatServletWebServerFactory.java:409) ~[spring-boot-2
.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFa
ctory.getWebServer(TomcatServletWebServerFactory.java:174) ~[spring-boot-2.0.2.R
ELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring
-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.onRefresh(ServletWebServerApplicationContext.java:152) ~[spring-boot-
2.0.2.RELEASE.jar:2.0.2.RELEASE]
        ... 9 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to initialize componen
t [StandardServer[-1]]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112) ~
[tomcat-embed-core-8.5.31.jar:8.5.31]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
~[tomcat-embed-core-8.5.31.jar:8.5.31]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:367) ~[tomcat-em
bed-core-8.5.31.jar:8.5.31]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initiali
ze(TomcatWebServer.java:107) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        ... 14 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache
.catalina.mbeans.MBeanFactory
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.j
ava:838) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) ~
[tomcat-embed-core-8.5.31.jar:8.5.31]
        ... 17 common frames omitted

E:\kiftd>

**Comment by KOHGYLW** [comment]
您好，这一问题可能是由于端口冲突导致的，您可以尝试在kiftd设置里换用一个端口再试。如果该问题仍无法解决，您可以将详细的问题截图发送至此，以便为您进一步排查问题所在。希望kiftd能够帮助到您！
