### ISSUE TITLE
打包下载为zip压缩包后，解压报错，试了软件和jar命令解压，都没能解决，求帮助。

### ISSUE THREAD

**Issue by wangqiantju** [KOHGYLW/kiftd#166]
您好，请问打包为zip下载后，用unarchiver解压会失败，也尝试其他文件解压工具也会失败。后来采用jar xvf 命令解压也会失败，但是解压出来的文件数量变多。报错如下：
lease-linux-x86_64-grid/locale/zh_CN/LC_MESSAGES/wrap.mo
  已创建:  0 安装包及源码/1 安装包/系统安装/凝思操作系统/
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:230)
	at java.util.zip.ZipFile.<init>(ZipFile.java:160)
	at java.util.zip.ZipFile.<init>(ZipFile.java:131)
	at sun.tools.jar.Main.list(Main.java:1115)
	at sun.tools.jar.Main.run(Main.java:293)
	at sun.tools.jar.Main.main(Main.java:1288)

备注：在这个文件夹下有一个大的iso文件，不知是不是这个原因。

请问有什么好的方法，能把我的这些文件全部解压出来？因为除了“0 安装包及源码”之外还有其他同级文件夹下的文档。感谢。

**Comment by wangqiantju** [comment]
部署的kiftd环境已经挂掉了，不能再下载了，现在只有这个压缩包有全部文件了。
