### ISSUE TITLE
Ubuntu Server -console 启动报错

### ISSUE THREAD

**Issue by schizobulia** [KOHGYLW/kiftd#58]
- 环境
操作系统	Ubuntu Server 18.04.1 LTS 64位
CPU	1 核
内存	1 GB
版本：kiftd-1.0.24-RELEASE.jar
- 错误
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/web/embedded/tomcat/TomcatServletWebServerFactory
        at kohgylw.kiftd.mc.ConsoleRunner.<init>(ConsoleRunner.java:44)
        at kohgylw.kiftd.mc.ConsoleRunner.build(ConsoleRunner.java:64)
        at kohgylw.kiftd.mc.MC.main(MC.java:37)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```
启动方式：
```
java -jar kiftd-1.0.24-RELEASE.jar -console
```

**Comment by jie12366** [comment]
老哥，这个怎么解决的

**Comment by schizobulia** [comment]
忘了...但不是应用程序的问题

**Comment by jie12366** [comment]
我太难了，咋启动不了。。

**Comment by schizobulia** [comment]
这个文档在哪来着,你发个链接我想想。ps: 可能是需要禁止图形界面的功能

**Comment by jie12366** [comment]
啥文档啊

**Comment by schizobulia** [comment]
这个程序的部署文档

**Comment by jie12366** [comment]
https://kohgylw.gitee.io/QuickStart.html

**Comment by schizobulia** [comment]
需要linux的部署文档 他首页只有win的部署文档

**Comment by jie12366** [comment]
我没看到。。。

**Comment by schizobulia** [comment]
你的部署环境是什么   你在哪里看到的 java -jar kiftd-1.0.24-RELEASE.jar -console 这个命令

**Comment by jie12366** [comment]
ubuntu16。我就是直接当java程序运行啊。就用了这个java -jar kiftd-1.0.24-RELEASE.jar

**Comment by schizobulia** [comment]
执行：java -jar kiftd-x.x.x-xxx.jar -start

**Comment by jie12366** [comment]
没用诶

**Comment by schizobulia** [comment]
所以还是那个错误吗

**Comment by jie12366** [comment]
是啊

**Comment by schizobulia** [comment]
你先自己解决吧  我现在没时间

**Comment by jie12366** [comment]
好哦，谢谢啦。
