### ISSUE TITLE
Cannot create a session after the response has been committed

### ISSUE THREAD

**Issue by wpf973** [KOHGYLW/kiftd#95]
TIME:
2020年04月29日 18:56:17
TYPE:
Exception
CONTENT:
java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3015)
	at org.apache.catalina.connector.Request.getSession(Request.java:2450)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:908)
	at kohgylw.kiftd.server.util.LogUtil.writeDownloadFileEvent(LogUtil.java:232)
	at kohgylw.kiftd.server.service.impl.FileServiceImpl.doDownloadFile(FileServiceImpl.java:338)
	at kohgylw.kiftd.server.controller.HomeController.downloadFile(HomeController.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
......

**Comment by KOHGYLW** [comment]
The question has been received and will be resolved in the next version.Thanks for feedback!

**Comment by KOHGYLW** [comment]
The new version (v1.0.29) has been released and fixed the issue you raised.Welcome to download experience!
